-- Field/ranger mobile (plan 2026-06-10) — A2: collection_stop + run metadata.
--
-- A stop is one crew visit: booking × waste stream. A booking with General +
-- Green + a Mattress yields three stops collected on different passes by
-- different crews. Stops are generated by the push-orders-to-optimoroute EF
-- at T-3 hard close (service role; no INSERT policy here by design).
--
-- The schema is routing-engine-agnostic: OptimoRoute supplies driver/sequence
-- today, but external_order_ref / driver_serial / stop_sequence are just data
-- and another engine (VROOM, Google) could populate them without UI changes.
-- A "run" is implicit — (driver_serial, collection date) — not a table.
--
-- Address/lat/lng/services are denormalised onto the stop so the field run
-- sheet NEVER joins booking → contacts (structural PII exclusion, CLAUDE.md
-- §4/§20) and sidesteps the authed-role multi-FK embed gotcha (§21).

CREATE TYPE stop_status AS ENUM (
  'Pending',
  'Completed',
  'Non-conformance',
  'Nothing Presented',
  'Cancelled'
);

CREATE TABLE collection_stop (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id          uuid NOT NULL REFERENCES booking(id) ON DELETE CASCADE,
  client_id           uuid NOT NULL REFERENCES client(id),
  stream              waste_stream NOT NULL,
  collection_date_id  uuid NOT NULL REFERENCES collection_date(id),
  status              stop_status NOT NULL DEFAULT 'Pending',

  -- Denormalised display fields (zero PII by construction)
  address             text,
  latitude            numeric,
  longitude           numeric,
  services_summary    jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- Routing-engine sync state
  external_order_ref  text UNIQUE,
  pushed_at           timestamptz,
  last_push_error     text,
  external_deleted_at timestamptz,

  -- Planned route data (pulled back after ops plan)
  driver_serial       text,
  driver_name         text,
  stop_sequence       integer,
  scheduled_at        time,
  routes_pulled_at    timestamptz,

  -- Closeout
  completed_at        timestamptz,
  completed_by        uuid REFERENCES profiles(id),
  cancelled_at        timestamptz,

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  UNIQUE (booking_id, stream)
);

COMMENT ON TABLE collection_stop IS
  'One crew visit: booking × waste stream. Generated by the '
  'push-orders-to-optimoroute EF at T-3 hard close. services_summary is '
  '[{name, qty}] for the stop''s stream only. external_order_ref is the '
  'routing-engine order id ({booking.ref}-{GEN|GRN|ANC|ID}).';

CREATE INDEX idx_collection_stop_date ON collection_stop(collection_date_id);
CREATE INDEX idx_collection_stop_driver_date ON collection_stop(driver_serial, collection_date_id);
CREATE INDEX idx_collection_stop_client ON collection_stop(client_id);
CREATE INDEX idx_collection_stop_pending ON collection_stop(status) WHERE status = 'Pending';

CREATE TRIGGER collection_stop_updated_at BEFORE UPDATE ON collection_stop
  FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER audit_collection_stop
  AFTER INSERT OR UPDATE OR DELETE ON collection_stop
  FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

-- ---------------------------------------------------------------------------
-- Stop state machine: Pending → {Completed, Non-conformance,
-- Nothing Presented, Cancelled}. Terminal states immutable. Mirrors the
-- booking state machine style (§7) — application code must never force it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION enforce_stop_state_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF OLD.status <> 'Pending' THEN
      RAISE EXCEPTION 'Invalid stop transition: % → % (terminal stop statuses are immutable)',
        OLD.status, NEW.status;
    END IF;
    -- From Pending every other status is reachable; no further check needed.
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_stop_state_transition
  BEFORE UPDATE OF status ON collection_stop
  FOR EACH ROW EXECUTE FUNCTION enforce_stop_state_transition();

-- ---------------------------------------------------------------------------
-- Booking rollup: when the LAST stop of a booking leaves Pending, derive the
-- booking status — exception wins: any NCN → Non-conformance, else any NP →
-- Nothing Presented, else Completed (over non-Cancelled stops). All-Cancelled
-- is a no-op (the booking-cancel path owns that case).
--
-- A trigger rather than server-action logic because three writers terminalise
-- stops (field closeout actions, the booking-status sync trigger below,
-- future admin corrections) and the rollup must be atomic with the stop write
-- regardless of writer. Runs as INVOKER: the field user's own
-- booking_field_update policy permits exactly the Scheduled → terminal
-- transitions this issues — defence in depth preserved. Never RAISEs: the
-- WHERE status = 'Scheduled' guard makes out-of-band booking states a silent
-- no-op instead of poisoning the stop write.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION rollup_booking_status_from_stops()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_pending  integer;
  v_ncn      integer;
  v_np       integer;
  v_live     integer;  -- non-Cancelled terminal stops
  v_rollup   booking_status;
BEGIN
  SELECT
    count(*) FILTER (WHERE status = 'Pending'),
    count(*) FILTER (WHERE status = 'Non-conformance'),
    count(*) FILTER (WHERE status = 'Nothing Presented'),
    count(*) FILTER (WHERE status <> 'Cancelled')
  INTO v_pending, v_ncn, v_np, v_live
  FROM collection_stop
  WHERE booking_id = NEW.booking_id;

  IF v_pending > 0 OR v_live = 0 THEN
    RETURN NULL;  -- stops still open, or everything cancelled — nothing to roll up
  END IF;

  v_rollup := CASE
    WHEN v_ncn > 0 THEN 'Non-conformance'::booking_status
    WHEN v_np  > 0 THEN 'Nothing Presented'::booking_status
    ELSE 'Completed'::booking_status
  END;

  UPDATE booking
  SET status = v_rollup
  WHERE id = NEW.booking_id
    AND status = 'Scheduled';

  RETURN NULL;
END;
$$;

CREATE TRIGGER rollup_booking_status_from_stops
  AFTER UPDATE OF status ON collection_stop
  FOR EACH ROW
  WHEN (NEW.status IS DISTINCT FROM OLD.status AND NEW.status <> 'Pending')
  EXECUTE FUNCTION rollup_booking_status_from_stops();

-- ---------------------------------------------------------------------------
-- Booking → stops sync. Two jobs in one trigger:
--
--  * Cancelled: cancel all Pending stops. Catches EVERY cancellation path
--    (resident, admin, handle-expired-payments cron) in one place; the
--    cancellation sweep EF then deletes the routing-engine orders.
--  * Terminal (Completed/NCN/NP) set directly on the booking — the legacy
--    per-booking closeout path, and admin overrides: close remaining Pending
--    stops to the same outcome so booking and stops can't drift during the
--    mixed-mode window (per-booking semantics = the whole booking shares one
--    outcome, so inheriting it per stop is faithful).
--
-- SECURITY DEFINER: residents (cancel path) have no UPDATE policy on
-- collection_stop, and neither do client/contractor staff — only the function
-- owner can write these rows on their behalf. Recursion-safe: when the rollup
-- trigger set the booking status, no stop is Pending, so the UPDATE here
-- matches zero rows and fires nothing.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION sync_stops_on_booking_status()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'Cancelled' THEN
    UPDATE collection_stop
    SET status = 'Cancelled', cancelled_at = now()
    WHERE booking_id = NEW.id AND status = 'Pending';
  ELSIF NEW.status IN ('Completed', 'Non-conformance', 'Nothing Presented') THEN
    UPDATE collection_stop
    SET status = NEW.status::text::stop_status,
        completed_at = CASE WHEN NEW.status = 'Completed' THEN now() END
    WHERE booking_id = NEW.id AND status = 'Pending';
  END IF;
  RETURN NULL;
END;
$$;

CREATE TRIGGER sync_stops_on_booking_status
  AFTER UPDATE OF status ON booking
  FOR EACH ROW
  WHEN (NEW.status IS DISTINCT FROM OLD.status)
  EXECUTE FUNCTION sync_stops_on_booking_status();

-- ---------------------------------------------------------------------------
-- RLS — same migration as the table, always.
-- ---------------------------------------------------------------------------
ALTER TABLE collection_stop ENABLE ROW LEVEL SECURITY;

-- Transitive SELECT: whoever can see the booking can see its stops (same
-- pattern as booking_item_select). Inherits the whole role matrix including
-- sub-client narrowing and resident own-booking scope. Stops carry no PII.
CREATE POLICY collection_stop_select ON collection_stop FOR SELECT
  USING (
    booking_id IN (SELECT id FROM booking)
  );

-- Field closeout: Pending → terminal only, own tenant, sub-client narrowed.
-- Ranger deliberately excluded from writes (has_role('field'), not
-- is_field_user()) — matches booking_field_update.
CREATE POLICY collection_stop_field_update ON collection_stop FOR UPDATE
  USING (
    client_id IN (SELECT accessible_client_ids())
    AND has_role('field'::app_role)
    AND status = 'Pending'::stop_status
    AND user_sub_client_allows_booking(booking_id)
  )
  WITH CHECK (
    status = ANY (ARRAY[
      'Completed'::stop_status,
      'Non-conformance'::stop_status,
      'Nothing Presented'::stop_status
    ])
  );

-- No INSERT/DELETE policies: only the push EF (service role) creates stops,
-- and stops are never deleted (booking CASCADE aside).

-- ---------------------------------------------------------------------------
-- Run-level metadata pulled from the routing engine — start/finish times and
-- depot labels per (driver, date) for the run-sheet header. Service-role
-- write only (pull EF); readable by any authenticated operational role.
-- ---------------------------------------------------------------------------
CREATE TABLE collection_run_meta (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_serial    text NOT NULL,
  date             date NOT NULL,
  driver_name      text,
  start_time       time,
  finish_time      time,
  depot_labels     jsonb NOT NULL DEFAULT '[]'::jsonb,
  routes_pulled_at timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  UNIQUE (driver_serial, date)
);

COMMENT ON TABLE collection_run_meta IS
  'Per-(driver, date) route metadata from the routing engine: start/finish '
  'times + depot stop labels for the run-sheet header. Crews lost this '
  'visibility when they left the OptimoRoute Driver app — this restores it.';

CREATE TRIGGER collection_run_meta_updated_at BEFORE UPDATE ON collection_run_meta
  FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE collection_run_meta ENABLE ROW LEVEL SECURITY;

CREATE POLICY collection_run_meta_select ON collection_run_meta FOR SELECT
  USING (
    is_field_user() OR is_client_staff() OR is_contractor_user()
  );
-- No INSERT/UPDATE/DELETE policies — pull EF (service role) owns writes.
